version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: bidmart-prometheus
    restart: unless-stopped
    profiles: ["monitoring"]
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: bidmart-grafana
    restart: unless-stopped
    profiles: ["monitoring"]
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  auction-service:
    image: ghcr.io/advprog-2026-b15-project/bidmart-auction:latest
    container_name: bidmart-auction
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JDBC_DATABASE_URL=${JDBC_DATABASE_URL}
      - JDBC_DATABASE_USERNAME=${JDBC_DATABASE_USERNAME}
      - JDBC_DATABASE_PASSWORD=${JDBC_DATABASE_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_SSL_ENABLED=${RABBITMQ_SSL_ENABLED}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - WALLET_SERVICE_URL=${WALLET_SERVICE_URL}

volumes:
  grafana-storage: