spring.application.name=bidmart-auction
server.port=8083

# database configuration
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/bidmart_auction}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:amimir}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# flyway
spring.flyway.enabled=true

# thymeleaf
spring.thymeleaf.cache=false

# rabbitmq event broker configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# service connectivity (API call external)
bidmart.wallet-service.url=${WALLET_SERVICE_URL:http://localhost:8084}
springdoc.swagger-ui.path=/swagger-ui.html
