spring.application.name=bidmart-auction
server.port=8083

# database configuration
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# flyway
spring.flyway.enabled=true

# thymeleaf
spring.thymeleaf.cache=false

# rabbitmq event broker configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# service connectivity (API call external)
bidmart.wallet-service.url=${WALLET_SERVICE_URL}
springdoc.swagger-ui.path=/swagger-ui.html

# redis configuration (upstash)
bidmart.redis.url=${REDIS_URL}
bidmart.redis.password=${REDIS_PASSWORD}

# scheduler
spring.task.scheduling.pool.size=2
