spring.application.name=bidmart-auction
server.port=8083

# database configuration
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/bidmart_auction}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:amimir}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# flyway
spring.flyway.enabled=true

# thymeleaf
spring.thymeleaf.cache=false
