name: Deploy to Green EC2

on:
  workflow_run:
    workflows:
      - "Deploy to Blue EC2"
    types:
      - completed
    branches:
      - main

jobs:
  deploy-green:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy docker-compose to Green EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GREEN_EC2_HOST }}
          username: ${{ secrets.GREEN_EC2_USERNAME }}
          key: ${{ secrets.GREEN_EC2_SSH_KEY }}
          source: "docker-compose.yml,config/"
          target: "~/"

      - name: Deploy to Green EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GREEN_EC2_HOST }}
          username: ${{ secrets.GREEN_EC2_USERNAME }}
          key: ${{ secrets.GREEN_EC2_SSH_KEY }}
          script: |
            docker compose pull
            docker compose up -d
